apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: pr-report-cronjob
  namespace: opengauss-pr-report
spec:
  schedule: "1 0 * * 1,3"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: report-job
            image: swr.cn-north-4.myhuaweicloud.com/opensourceway/opengauss/pr-report:opengauss-4ceb37
            imagePullPolicy: IfNotPresent
            env:
            - name: access_token
              valueFrom:
                secretKeyRef:
                  key: access_token
                  name: pr-report-secret
            - name: host
              valueFrom:
                secretKeyRef:
                  key: host
                  name: pr-report-secret
            - name: port
              valueFrom:
                secretKeyRef:
                  key: port
                  name: pr-report-secret
            - name: user
              valueFrom:
                secretKeyRef:
                  key: user
                  name: pr-report-secret
            - name: pwd
              valueFrom:
                secretKeyRef:
                  key: pwd
                  name: pr-report-secret
            - name: from
              valueFrom:
                secretKeyRef:
                  key: from
                  name: pr-report-secret
            - name: TZ
              value: Asia/Shanghai
            resources:
              limits:
                cpu: 2000m
                memory: 4000Mi
              requests:
                cpu: 500m
                memory: 500Mi
          restartPolicy: Never