resources:
- deployment.yaml
- ingress.yaml
- service.yaml
- pvc.yaml
- mirror-manager-only.yaml
- cron-mm2-crawler.yaml
commonAnnotations:
  kubernetes.ops.cluster: openeuler-hk-cluster
  kubernetes.ops.email: chenzeng765@163.com
  kubernetes.ops.os.base: fedora
  kubernetes.ops.owner: chenzeng
  kubernetes.ops.region: hk
namespace: openeuler-mirrorlist-server
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/openeuler/mirror-manager
  newTag: 1cc02c18fc0dde32c99f17e793f5de9f3edc8df1
