---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    everest.io/disk-volume-type: GPSSD
  name: openeuler-sync-bot-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300Gi
  storageClassName: csi-disk
  volumeMode: Filesystem
  volumeName: pv-evs-sync-bot-from-old-cluster
