---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: botinfo
  namespace: bot
spec:
  replicas: 0
  selector:
    matchLabels:
      app: botinfo
  template:
    metadata:
      labels:
        app: botinfo
    spec:
      containers:
        - args:
            - --stderrthreshold=0
          env:
            - name: GITEE_TOKEN
              valueFrom:
                secretKeyRef:
                  key: gitee_token
                  name: bot-secret
            - name: WEBHOOK_SECRET
              valueFrom:
                secretKeyRef:
                  key: webhook_secret
                  name: bot-secret
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  key: database_username
                  name: bot-secret
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: database_password
                  name: bot-secret
            - name: GITEE_OAUTH2_SECRET
              valueFrom:
                secretKeyRef:
                  key: gitee_oauth2_secret
                  name: bot-secret
            - name: GITEE_OAUTH2_CLIENT_CODE
              valueFrom:
                secretKeyRef:
                  key: gitee_oauth2_client_code
                  name: bot-secret
            - name: WEBSITE_URL
              value: https://openeuler.org/
          image: swr.cn-north-4.myhuaweicloud.com/opensourceway/common/ci-bot:01a4d08480fca787186b71fcc7e4f0324a54a721.1621594500
          imagePullPolicy: IfNotPresent
          name: botinfod
          volumeMounts:
            - mountPath: /bot/config.yaml.ro
              name: configmap-volume
              subPath: config.yaml
            - mountPath: /bot/_service
              name: bot-service-configmap
              subPath: _service
          command:
            - /bin/sh
            - -c
            - |
              apk add vim
              apk add htop
              cp /bot/config.yaml.ro /bot/config.yaml
              chmod 0666 /bot/config.yaml
              echo "$(sed '1c nameserver 8.8.8.8' /etc/resolv.conf)" > /etc/resolv.conf
              sleep 3600000
      volumes:
        - configMap:
            name: bot-configmap
          name: configmap-volume
        - configMap:
            name: bot-service-configmap
          name: bot-service-configmap
