resources:
- https://github.com/opensourceways/app-bugzilla/deploy?ref=main
- ingress.yaml
commonLabels:
  app: bugzilla
  owner: caozhi
commonAnnotations:
  owner: caozhi
  email: "caozhi1214@gmail.com"
namespace: bugzilla
patchesStrategicMerge:
- deployment.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.ap-southeast-1.myhuaweicloud.com/opensourceway/bugzilla
  newName: swr.cn-north-4.myhuaweicloud.com/opensourceway/openeuler/bugzilla
  newTag: bf490dc98cd7f40ca24473bc6e90274c6b9a386e.1612088275
