apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: datastat-openeuler-tls
  namespace: opendesign-datapertus
spec:
  keysMap:
    ca.crt:
      key: server.crt
      path: secrets/data/openeuler/openeuler-org-tls
    tls.crt:
      key: server.crt
      path: secrets/data/openeuler/openeuler-org-tls
    tls.key:
      key: server.key
      path: secrets/data/openeuler/openeuler-org-tls
  name: datastat-openeuler-tls