resources:
- deployment.yaml
- namespace.yaml
- service.yaml
- ingress.yaml
- secrets.yaml
commonLabels:
  app: openeuler-website-v2
commonAnnotations:
  email: 245462755@qq.com
  owner: zhengyuhang
namespace: website-v2
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/openeuler/openeuler-website-backend
  newTag: 4e873d57d82ccce861cb1661310326
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/openeuler/openeuler-website-frontend
  newTag: a6fec19be3ce1a0cf69601cf8b888a137027bd46
