apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: patchwork-file-data
  namespace: patchwork
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 12Gi
  storageClassName: csi-nas
  volumeMode: Filesystem

