apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: patchwork-share-disk-volume
  namespace: patchwork
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: csi-disk
  volumeMode: Filesystem

