---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: repo-mirrorbits
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: repo-mirrorbits
    spec:
      containers:
        - name: repo-mirrorbits
          image: swr.cn-north-4.myhuaweicloud.com/opensourceway/openeuler/repo-mirrorbits:25434bcc58bff7a3f712226c4923f2daa616dd96
          volumeMounts:
            - mountPath: /repo/openeuler
              name: data-volume
            - mountPath: /etc/mirrorbits.conf
              name: mirrorbits-configmap-volume
              subPath: mirrorbits.conf
            - mountPath: /usr/local/etc/GeoIP.conf
              name: mirrorbits-secrets-volume
              subPath: geoip_conf
          command:
            - /bin/sh
            - -c
            - |
              mkdir -pv /usr/local/share/GeoIP
              geoipupdate -v
              exec /usr/bin/mirrorbits daemon --config /etc/mirrorbits.conf -debug
          env:
            - name: REDIS_ADDRESS_PORT
              valueFrom:
                secretKeyRef:
                  name: mirrorbits-secrets
                  key: redis-address-port
            - name: REDIS_PWD
              valueFrom:
                secretKeyRef:
                  name: mirrorbits-secrets
                  key: redis-pwd
            - name: TZ
              value: Asia/Shanghai
          livenessProbe:               #存活探针
            initialDelaySeconds: 60    #延迟加载时间
            periodSeconds: 5           #重试时间间隔
            timeoutSeconds: 5          #超时时间设置
            failureThreshold: 3        #探测失败的重试次数
            httpGet:
              path: /healthz
              port: 8080
        - name: mirror-sync
          image: swr.cn-north-4.myhuaweicloud.com/opensourceway/openeuler/repo-mirrorbits:25434bcc58bff7a3f712226c4923f2daa616dd96
          command:
            - /bin/sh
            - -c
            - |
              cd /
              exec python3 /refresh_mirrors.py
          env:
            - name: TZ
              value: Asia/Shanghai
        - name: rsync-server
          image: swr.cn-north-4.myhuaweicloud.com/opensourceway/common/repo-client:474bf9a0c93f0ba0be97b593f5e2e79bbad63509
          volumeMounts:
            - mountPath: /etc/rsyncd.secrets.ro
              name: mirrorbits-secrets-volume
              subPath: rsyncd_secrets
            - mountPath: /etc/rsyncd.server.secrets.ro
              name: mirrorbits-secrets-volume
              subPath: rsyncd_server_secrets
            - mountPath: /repo/openeuler
              name: data-volume
            - mountPath: /root/.ssh/authorized_keys.ro
              name: mirrorbits-configmap-volume
              subPath: ssh.pub
          env:
            - name: TARGET_DIR
              value: "/repo/openeuler"
            - name: RSYNC_INTERNAL
              value: "21600"
            - name: SYNC_HOST
              value: "rsync://root@121.36.97.194/openeuler"
            - name: ADDITIONAL_PARAMETERS
              #only sync the iso and its related files.
              value: "-m --delete --include=*/ --include=*.iso --include=*.iso.sha256sum --exclude=*"
          command:
            - /bin/sh
            - -c
            - |
              cp -a /etc/rsyncd.secrets.ro /etc/rsyncd.secrets
              cp -a /etc/rsyncd.server.secrets.ro /etc/rsyncd.server.secrets
              chmod 0400 /etc/rsyncd.secrets
              chmod 0400 /etc/rsyncd.server.secrets
              exec tini -- entrypoint.sh
          resources:
            requests:
              cpu: 2000m
              memory: 4000Mi
      volumes:
        - name: mirrorbits-configmap-volume
          configMap:
            name: mirrorbits-configmap
        - name: mirrorbits-secrets-volume
          secret:
            secretName: mirrorbits-secrets
        - name: data-volume
          persistentVolumeClaim:
            claimName: openeuler-data-volume
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
spec:
  replicas: 1
  serviceName: redis
  selector:
    matchLabels:
      name: redis
  template:
    metadata:
      labels:
        name: redis
    spec:
      initContainers:
      - name: init-redis
        image: busybox
        command: ['sh', '-c', 'mkdir -p /data/redis/log/;mkdir -p /data/redis/conf/;mkdir -p /data/redis/data/']
        volumeMounts:
        - name: redis-data-volume
          mountPath: /data/redis/
      containers:
      - name: redis
        image: swr.cn-north-4.myhuaweicloud.com/opensourceway/common/redis:rc-alpine3.12
        imagePullPolicy: IfNotPresent
        command: ['redis-server', '/data/redis/conf/redis.conf']
        ports:
        - containerPort: 6379
          name: redis
          protocol: TCP
        resources:
          limits:
            cpu: 4000m
            memory: 10240Mi
          requests:
            cpu: 2000m
            memory: 2048Mi
        livenessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 300
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        volumeMounts:
        - name: mirrorbits-configmap-volume
          mountPath: /data/redis/conf/redis.conf
          subPath: redis.conf
        - name: redis-data-volume
          mountPath: /data/redis/
      volumes:
        - name: mirrorbits-configmap-volume
          configMap:
            name: mirrorbits-configmap
        - name: redis-data-volume
          persistentVolumeClaim:
            claimName: redis-data-volume
