resources:
- deployment.yaml
- secrets.yaml
- namespace.yaml
- es-secrets.yaml
- ingress.yaml
- oauth-proxy.yaml
- cronjob.yaml
- openeuler-ci.yaml
- service.yaml
- pvc.yaml
commonLabels:
  app: openeuler-jenkins
commonAnnotations:
  email: caozhi1214@gmail.com
  owner: caozhi
namespace: jenkins
images:
- name: swr.cn-north-4.myhuaweicloud.com/openeuler/bak-jenkins
  newTag: c94969284e4ec1a2b9bdadd3abee8c3e9e369448
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/openeuler/openeuler-ci
  newTag: bb4241e8f16fdd2dd0978c6bbc5fae5bafd36f06
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
