---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: flexvolume-huawei.com/fuxivol
    volume.kubernetes.io/storage-resizer: everest-csi-resizer
  labels:
    app: openeuler-jenkins
    app.kubernetes.io/component: jenkins-master
    app.kubernetes.io/instance: openeuler-cn-north4-jenkins-2
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: jenkins
    failure-domain.beta.kubernetes.io/region: cn-north-4
    failure-domain.beta.kubernetes.io/zone: cn-north-4c
  name: jenkins
  namespace: jenkins
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
  storageClassName: ssd

