---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-agent
  namespace: jenkins
spec:
  ports:
  - name: http
    nodePort: 30080
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: slavelistener
    nodePort: 30050
    port: 50000
    protocol: TCP
    targetPort: 50000
  selector:
    app: openeuler-jenkins
    app.kubernetes.io/component: jenkins-master
    app.kubernetes.io/instance: jenkins
  sessionAffinity: None
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: jenkins
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    nodePort: 30986
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: slavelistener
    nodePort: 30233
    port: 50000
    protocol: TCP
    targetPort: 50000
  selector:
    app: openeuler-jenkins
    app.kubernetes.io/component: jenkins-master
    app.kubernetes.io/instance: jenkins
  sessionAffinity: None
  type: NodePort
