---
apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: dockerhub-secret
  namespace: openeuler-dockerhub
spec:
  name: dockerhub-secret
  keysMap:
    nginx.htpasswd:
      path: secrets/data/openeuler/dockerhub-cn4
      key: nginx.htpasswd