resources:
- https://github.com/opensourceways/app-pkgmanage/deploy?ref=master
- ingress.yaml
commonLabels:
  app: openeuler-packagemanage-release
namespace: packagemanage-release
nameSuffix: -release
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: opensourceway/dbgetinit
  newName: swr.cn-north-4.myhuaweicloud.com/opensourceway/openeuler/dbgetinit
  newTag: 8e7271df48d2170e31e68331c8f18eccbe865bfa.1685621885
- name: opensourceway/packagemanage
  newName: swr.cn-north-4.myhuaweicloud.com/opensourceway/openeuler/packagemanage
  newTag: 8e7271df48d2170e31e68331c8f18eccbe865bfa.1685621885
- name: opensourceway/pkgmanageweb
  newName: swr.cn-north-4.myhuaweicloud.com/opensourceway/openeuler/pkgmanageweb
  newTag: aa428d27809fcf79e5f1f3ef31ed2bb4b96b6f28.1675769056
