---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/permanent-redirect: https://docs.openeuler.org/en/
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: letsencrypt-issuer
  name: openeuler-docs-ingress
spec:
  tls:
    - hosts:
        - docs.ru.openeuler.org
      secretName: website-docs-ru-lts
  rules:
    - host: docs.ru.openeuler.org
      http:
        paths:
          - backend:
              serviceName: website-docs-service
              servicePort: 80
            path: /
