resources:
- namespace.yaml
- secrets.yaml
- service.yaml
- ingress.yaml
- deployment.yaml
commonLabels:
  name: website-docs
commonAnnotations:
  kubernetes.ops.cluster: openeuler-mos-cce
  kubernetes.ops.email: 845831435@qq.com
  kubernetes.ops.os.base: openeuler
  kubernetes.ops.owner: wangxing
  kubernetes.ops.region: mos
namespace: website-docs
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/openeuler/openeuler-website-docs-ru
  newTag: v1.0.20230508082002
