---
apiVersion: v1
kind: Service
metadata:
  name: website-docs-service
  namespace: website-docs
spec:
  ports:
    - name: website-docs
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: website-docs
  type: ClusterIP
