apiVersion: v1
kind: Service
metadata:
  annotations:
    kubernetes.io/elb.class: union
    kubernetes.io/elb.id: 161185be-1794-452b-82ca-647db0e9c5b1
    kubernetes.io/elb.lb-algorithm: ROUND_ROBIN
  name: openeuler-service
  namespace: repo2
spec:
  clusterIP: 10.247.75.17
  externalTrafficPolicy: Cluster
  loadBalancerIP: 121.36.97.194
  ports:
  - name: nginx-repo-https
    nodePort: 31303
    port: 443
    protocol: TCP
    targetPort: 443
  - name: nginx-repo-http
    nodePort: 30941
    port: 80
    protocol: TCP
    targetPort: 80
  - name: rsync-server-port
    nodePort: 32063
    port: 873
    protocol: TCP
    targetPort: 873
  - name: rsync-ssh-server-port
    nodePort: 31337
    port: 22
    protocol: TCP
    targetPort: 22
  selector:
    app: repo-nginx-pod
  sessionAffinity: None
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kubernetes.io/elb.class: union
    kubernetes.io/elb.id: fa59225b-7d41-4612-aad7-27e971995a88
    kubernetes.io/elb.lb-algorithm: ROUND_ROBIN
  name: openeuler-service-for-hk-repo
  namespace: repo2
spec:
  externalTrafficPolicy: Cluster
  loadBalancerIP: 121.36.1.92
  ports:
    - name: rsync-server-port
      port: 873
      protocol: TCP
      targetPort: 873
  selector:
    app: repo-nginx-pod
  sessionAffinity: None
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kubernetes.io/elb.class: union
    kubernetes.io/elb.id: b5c299a6-1ae4-448d-8cd4-dd2ea67a6fac
    kubernetes.io/elb.lb-algorithm: ROUND_ROBIN
  name: openeuler-service-for-paris-rsync
  namespace: repo2
spec:
  loadBalancerIP: 114.116.230.90
  ports:
  - name: rsync-server-port
    port: 873
    protocol: TCP
    targetPort: 873
  selector:
    app: repo-nginx-pod
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: sbom-repo-service
  namespace: repo2
spec:
  ports:
  - name: http-port
    port: 8080
    targetPort: 15551
  selector:
    app: repo-nginx-pod
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: repo-archives-service
  namespace: repo2
spec:
  externalName: openeuler-service.archives-repo.svc.cluster.local
  type: ExternalName

