resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- secrets.yaml
commonLabels:
  app: osi-task-manager
  owner: zhangjianjun
commonAnnotations:
  email: 841670711@qq.com
  owner: zhangjianjun
namespace: osi-task-manager
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/openeuler/osi-task-manager
  newTag: 39ed22c7c15a60da40ab3cea7068a683fa14f1a7
