resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- secrets.yaml
- cronjob.yaml
- ingress.yaml
commonLabels:
  app: openeuler-meetingserver
  owner: liuqi
commonAnnotations:
  email: 469227928@qq.com
  owner: liuqi
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: meetingserver
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/openeuler/app-meeting-server
  newTag: 6927f64f1b863001b024150a356e7f4eeefbe5c0
