apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- ingress.yaml
- service.yaml
commonAnnotations:
  kubernetes.ops.cluster: openeuler-hk-new
  kubernetes.ops.email: duanpengjie@huawei.com
  kubernetes.ops.os.base: alpine
  kubernetes.ops.owner: duanpengjie
  kubernetes.ops.region: hk
commonLabels:
  app: compass-ci-api
namespace: compass-ci