resources:
- namespace.yaml
- ingress.yaml
- service.yaml
- deployment.yaml
namespace: openeuler-quickissue-website
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/openeuler/openeuler-quickissue
  newTag: fb7a837502fe0ecb7038f42671cddc3d5e0ce6c9
