---
apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: openeuler-reproducible-secret
  namespace: openeuler-reproducible
spec:
  name: openeuler-reproducible-secret
  keysMap:
    host_user:
      path: secrets/data/openeuler/openeuler-reproducible
      key: host_user
    host_password:
      path: secrets/data/openeuler/openeuler-reproducible
      key: host_password