resources:
  - ingress.yaml
  - www-ingress.yaml
  - namespace.yaml
  - cibot-service.yaml
  - openlookeng-website-frontend-service.yaml
  - clasign-ingress.yaml
  - clasign-secrets.yaml
  - tls.yaml
commonLabels:
  app: openlookeng-website
commonAnnotations:
  owner: caozhi
  email: "caozhi1214@gmail.com"
patchesJson6902:
  - target:
      group: ""
      version: v1
      kind: Service
      name: openlookeng-website-frontend-service
    path: selector.yaml
  - target:
      group: ""
      version: v1
      kind: Service
      name: openlookeng-bot-internal
    path: selector.yaml