---
apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: doc-search-secrets
  namespace: openeuler-doc-search
spec:
  name: doc-search-secrets
  keysMap:
    host:
      path: secrets/data/openeuler/doc-search
      key: host
    username:
      path: secrets/data/openeuler/doc-search
      key: username
    password:
      path: secrets/data/openeuler/doc-search
      key: password
    port:
      path: secrets/data/openeuler/doc-search
      key: port
    system:
      path: secrets/data/openeuler/doc-search
      key: system
    depp:
      path: secrets/data/openeuler/doc-search
      key: depp
    teshost:
      path: secrets/data/openeuler/doc-search
      key: teshost
    tesport:
      path: secrets/data/openeuler/doc-search
      key: tesport
    tesusername:
      path: secrets/data/openeuler/doc-search
      key: tesusername
    tespassword:
      path: secrets/data/openeuler/doc-search
      key: tespassword
    kneed:
      path: secrets/data/openeuler/doc-search
      key: kneed
    kbootstrap:
      path: secrets/data/openeuler/doc-search
      key: kbootstrap
    kgroup:
      path: secrets/data/openeuler/doc-search
      key: kgroup
    FORUMDOMAIM:
      path: secrets/data/openeuler/doc-search
      key: FORUMDOMAIM

---
apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: doc-search-tls
  namespace: openeuler-doc-search
spec:
  name: doc-search-tls
  keysMap:
    ca.crt:
      path: secrets/data/openeuler/doc-search
      key: server.crt
    tls.crt:
      path: secrets/data/openeuler/doc-search
      key: server.crt
    tls.key:
      path: secrets/data/openeuler/doc-search
      key: server.key
