resources:
- cronjob.yaml
- openeuler-ci.yaml
- namespace.yaml
- ingress.yaml
- oauth-proxy.yaml
namespace: jenkins-internal-service
images:
- name: swr.cn-north-4.myhuaweicloud.com/openeuler/bak-jenkins
  newTag: e6e192f6df0df85df93f4cefce4e22a920046420
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/openeuler/openeuler-ci
  newTag: cddca53736e6d3c193a087fd1d6fd4661c7f4243
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
