resources:
- deployment.yaml
- configmap.yaml
- service.yaml
commonAnnotations:
  kubernetes.ops.cluster: openeuler-hk-cluster
  kubernetes.ops.email: zjm.514@qq.com
  kubernetes.ops.os.base: Alpine
  kubernetes.ops.owner: zhaojiaming
  kubernetes.ops.region: hk
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openeuler-software-pkg
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/openeuler/software-package-message-server
  newTag: v1.0.20230616150316
