apiVersion: v1
kind: Service
metadata:
  name: message-server-service
  namespace: openeuler-software-pkg
spec:
  ports:
  - name: httpport
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: message-server
  type: ClusterIP