---
apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: rsync-secrets
spec:
  name: rsync-secrets
  keysMap:
    rsyncd-secrets:
      path: secrets/data/openeuler/rsync
      key: rsyncd-secrets
---
apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: obs-server-host-secret
  namespace: dailybuild
spec:
  name: obs-server-host-secret
  keysMap:
    host-user:
      path: secrets/data/openeuler/obs-server-secret
      key: host-user
    host-password:
      path: secrets/data/openeuler/obs-server-secret
      key: host-password
    host-name-155:
      path: secrets/data/openeuler/obs-server-secret
      key: host-name-155
    host-name-32:
      path: secrets/data/openeuler/obs-server-secret
      key: host-name-32
    host-name-95:
      path: secrets/data/openeuler/obs-server-secret
      key: host-name-95