resources:
- https://github.com/opensourceways/app-pkgmanage/deploy?ref=debug
- ingress.yaml
commonLabels:
  app: openeuler-packagemanage-debug
nameSuffix: -debug
namespace: packagemanage-debug
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: opensourceway/dbgetinit
  newName: swr.cn-north-4.myhuaweicloud.com/opensourceway/openeuler/dbgetinit
  newTag: d08a16f788bf58fa7837b6a6978664292ab8140f.1667898934
- name: opensourceway/packagemanage
  newName: swr.cn-north-4.myhuaweicloud.com/opensourceway/openeuler/packagemanage
  newTag: d08a16f788bf58fa7837b6a6978664292ab8140f.1667898934
- name: opensourceway/pkgmanageweb
  newName: swr.cn-north-4.myhuaweicloud.com/opensourceway/openeuler/pkgmanageweb
  newTag: c303217aefee434b3570b22eed02df478c9ea8c9.1687254206
