resources:
- deployment.yaml
- service.yaml
- ingress.yaml
commonAnnotations:
  kubernetes.ops.cluster: openeuler-hk-cluster
  kubernetes.ops.email: 845831435@qq.com
  kubernetes.ops.os.base: openEuler
  kubernetes.ops.owner: wangxing
  kubernetes.ops.region: hk
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openeuler-easyeditor
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/easyeditor/website
  newTag: v1.0.20230525203859
