resources:
- openeuler-infrastructure-slaves.yaml
- secrets.yaml
commonLabels:
  app: openeuler-jenkins
  owner: caozhi
commonAnnotations:
  email: caozhi1214@gmail.com
  owner: caozhi
namespace: jenkins
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/common/openeuler_infra_check
  newName: swr.cn-north-4.myhuaweicloud.com/opensourceway/common/openeuler_infra_check_image
  newTag: "20221025"
