---
apiVersion: v1
kind: Service
metadata:
  name: copr-backend
  namespace: fedora-copr-prod
spec:
  ports:
    - name: httpd
      port: 5002
      protocol: TCP
      targetPort: 5002
      nodePort: 31890
  selector:
    component: copr-backend
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: copr-backend
  namespace: fedora-copr-prod
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      component: copr-backend
  template:
    metadata:
      labels:
        component: copr-backend
    spec:
      nodeSelector:
        usage: test
        os.architecture: amd64
      imagePullSecrets:
      - name: huawei-swr-image-pull-secret
      initContainers:
        - name: init-backend-resalloc
          image: swr.cn-north-4.myhuaweicloud.com/opensourceway/copr/alpine-nc:v1.20230217
          command: [ "sh", "-c", "until nc -z copr-resalloc.fedora-copr-prod.svc.cluster.local 49100; do echo waiting for resalloc service ; sleep 2; done;" ]
      containers:
        - image: swr.cn-north-4.myhuaweicloud.com/opensourceway/copr/backend_httpd:v1.0.20230217145102
          imagePullPolicy: IfNotPresent
          name: httpd
          livenessProbe:
            tcpSocket:
              port: 5002
            initialDelaySeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 5002
            initialDelaySeconds: 5
            timeoutSeconds: 5
          resources:
            requests:
              cpu: 200m
              memory: 200Mi
            limits:
              cpu: 1000m
              memory: 1000Mi
          ports:
            - containerPort: 5002
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/copr/public_html/results
              name: copr-backend-data
        - image: swr.cn-north-4.myhuaweicloud.com/opensourceway/copr/backend:v1.0.20230217181430
          imagePullPolicy: IfNotPresent
          name: log
          args: ["/usr/bin/copr_run_logger.py"]
          resources:
            requests:
              cpu: 200m
              memory: 200Mi
            limits:
              cpu: 1000m
              memory: 1000Mi
          volumeMounts:
            - mountPath: /etc/nginx/conf.d/copr-be.conf
              name: copr-secrets
              subPath: backend_copr-be.conf
            - mountPath: /var/lib/copr/public_html/results
              name: copr-backend-data
            - mountPath: /etc/copr/copr-be.conf
              name: copr-secrets
              subPath: backend_copr-be.conf
        - image: swr.cn-north-4.myhuaweicloud.com/opensourceway/copr/backend:v1.0.20230217181430
          imagePullPolicy: IfNotPresent
          name: action
          args: ["/run-backend", "--sign-host", "copr-keygen", "/usr/bin/copr-run-dispatcher", "actions"]
          resources:
            requests:
              cpu: 200m
              memory: 200Mi
            limits:
              cpu: 8000m
              memory: 8000Mi
          volumeMounts:
            - mountPath: /etc/copr/copr-be.conf
              name: copr-secrets
              subPath: backend_copr-be.conf
            - mountPath: /var/lib/copr/public_html/results
              name: copr-backend-data
        - image: swr.cn-north-4.myhuaweicloud.com/opensourceway/copr/backend:v1.0.20230217181430
          imagePullPolicy: IfNotPresent
          name: build
          args: ["/run-backend", "--sign-host", "copr-keygen", "/usr/bin/copr-run-dispatcher", "builds"]
          resources:
            requests:
              cpu: 200m
              memory: 200Mi
            limits:
              cpu: 8000m
              memory: 8000Mi
          volumeMounts:
            - mountPath: /home/copr/.ssh/builder_config
              name: copr-backend
              subPath: builder_config
            - mountPath: /home/copr/.ssh/id_rsa
              name: copr-secrets
              subPath: backend_id_rsa
            - mountPath: /home/copr/.ssh/id_rsa.pub
              name: copr-secrets
              subPath: backend_id_rsa.pub
            - mountPath: /var/lib/copr/public_html/results
              name: copr-backend-data
            - mountPath: /etc/copr/copr-be.conf
              name: copr-secrets
              subPath: backend_copr-be.conf
      volumes:
        - name: copr-backend
          configMap:
            name: copr-backend
        - name: copr-backend-data
          persistentVolumeClaim:
            claimName: copr-backend-data
        - name: copr-secrets
          secret:
            secretName: copr-secrets