---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: backend-cronjob-week
spec:
  schedule: "0 0 * * 0"
  jobTemplate:
    spec:
      template:
        spec:
          affinity:
            podAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                  - key: component
                    operator: In
                    values:
                    - copr-backend
                topologyKey: kubernetes.io/hostname
          containers:
          - image: swr.cn-north-4.myhuaweicloud.com/opensourceway/copr/backend:v1.0.20230313190328
            name: backend-cronjob
            args: ["sudo", "/etc/cron.weekly/copr-backend"]
            volumeMounts:
              - mountPath: /home/copr/.ssh/builder_config
                name: copr-backend
                subPath: builder_config
              - mountPath: /home/copr/.ssh/id_rsa
                name: copr-secrets
                subPath: backend_id_rsa
              - mountPath: /home/copr/.ssh/id_rsa.pub
                name: copr-secrets
                subPath: backend_id_rsa.pub
              - mountPath: /var/lib/copr/public_html/results
                name: copr-backend-data
              - mountPath: /etc/copr/copr-be.conf
                name: copr-secrets
                subPath: backend_copr-be.conf
          volumes:
            - name: copr-backend
              configMap:
                name: copr-backend
            - name: copr-backend-data
              persistentVolumeClaim:
                claimName: copr-backend-data
            - name: copr-secrets
              secret:
                secretName: copr-secrets
          restartPolicy: OnFailure
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: backend-cronjob-daily
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          affinity:
            podAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                  - key: component
                    operator: In
                    values:
                    - copr-backend
                topologyKey: kubernetes.io/hostname
          containers:
          - image: swr.cn-north-4.myhuaweicloud.com/opensourceway/copr/backend:v1.0.20230313190328
            name: backend-cronjob
            args: ["sudo", "/etc/cron.daily/copr-backend"]
            volumeMounts:
              - mountPath: /home/copr/.ssh/builder_config
                name: copr-backend
                subPath: builder_config
              - mountPath: /home/copr/.ssh/id_rsa
                name: copr-secrets
                subPath: backend_id_rsa
              - mountPath: /home/copr/.ssh/id_rsa.pub
                name: copr-secrets
                subPath: backend_id_rsa.pub
              - mountPath: /var/lib/copr/public_html/results
                name: copr-backend-data
              - mountPath: /etc/copr/copr-be.conf
                name: copr-secrets
                subPath: backend_copr-be.conf
          volumes:
            - name: copr-backend
              configMap:
                name: copr-backend
            - name: copr-backend-data
              persistentVolumeClaim:
                claimName: copr-backend-data
            - name: copr-secrets
              secret:
                secretName: copr-secrets
          restartPolicy: OnFailure
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: distgit-cronjob-month
spec:
  schedule: "0 0 1 * *"
  jobTemplate:
    spec:
      template:
        spec:
          affinity:
            podAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                  - key: component
                    operator: In
                    values:
                    - copr-distgit
                topologyKey: kubernetes.io/hostname
          containers:
          - image: swr.cn-north-4.myhuaweicloud.com/opensourceway/copr/distgit:v1.0.20230313191102
            name: distgit-cronjob
            args: ["sudo", "/etc/cron.monthly/copr-dist-git"]
            volumeMounts:
              - mountPath: /var/lib/dist-git
                name: copr-distgit-data
              - mountPath: /etc/copr/copr-dist-git.conf
                name: copr-secrets
                subPath: distgit_copr-dist-git.conf
              - name: logs
                mountPath: /var/lib/copr-dist-git
              - name: locks
                mountPath: /var/lock/copr-dist-git
          volumes:
            - name: copr-distgit-data
              persistentVolumeClaim:
                claimName: copr-distgit-data
            - name: copr-distgit
              configMap:
                name: copr-distgit
            - name: logs
              persistentVolumeClaim:
                claimName: copr-distgit-logs
            - name: locks
              persistentVolumeClaim:
                claimName: copr-distgit-locks
            - name: copr-secrets
              secret:
                secretName: copr-secrets
          restartPolicy: OnFailure
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: frontend-cronjob-hourly
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          affinity:
            podAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                  - key: component
                    operator: In
                    values:
                    - copr-frontend
                topologyKey: kubernetes.io/hostname
          containers:
          - image: swr.cn-north-4.myhuaweicloud.com/opensourceway/copr/frontend:v1.0.20230313191521
            name: frontend-cronjob
            command:
            - /bin/sh
            - -c
            - sudo /etc/cron.hourly/copr-frontend; sudo /etc/cron.hourly/copr-frontend-optional
            volumeMounts:
            - mountPath: /usr/share/copr/data
              name: copr-frontend-search-data
            - mountPath: /etc/copr/copr.conf
              name: copr-secrets
              subPath: frontend_copr.conf
          volumes:
            - name: copr-frontend-search-data
              persistentVolumeClaim:
                claimName: copr-frontend-search-data
            - name: copr-secrets
              secret:
                secretName: copr-secrets
          restartPolicy: OnFailure
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: frontend-cronjob-daily
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          affinity:
            podAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                  - key: component
                    operator: In
                    values:
                    - copr-frontend
                topologyKey: kubernetes.io/hostname
          containers:
          - image: swr.cn-north-4.myhuaweicloud.com/opensourceway/copr/frontend:v1.0.20230313191521
            name: frontend-cronjob
            command:
            - /bin/sh
            - -c
            - sudo /etc/cron.daily/copr-frontend; sudo /etc/cron.daily/copr-frontend-optional
            volumeMounts:
            - mountPath: /usr/share/copr/data
              name: copr-frontend-search-data
            - mountPath: /etc/copr/copr.conf
              name: copr-secrets
              subPath: frontend_copr.conf
          volumes:
            - name: copr-frontend-search-data
              persistentVolumeClaim:
                claimName: copr-frontend-search-data
            - name: copr-secrets
              secret:
                secretName: copr-secrets
          restartPolicy: OnFailure
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: keygen-cronjob-daily
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          affinity:
            podAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                  - key: component
                    operator: In
                    values:
                    - copr-keygen
                topologyKey: kubernetes.io/hostname
          containers:
          - image: swr.cn-north-4.myhuaweicloud.com/opensourceway/copr/keygen-signd:v1.0.20230313192011
            name: keygen-cronjob
            args: ["sudo", "/etc/cron.daily/copr-keygen"]
            volumeMounts:
              - mountPath: /var/lib/copr-keygen
                name: copr-keygen-data
              - mountPath: /etc/httpd/conf.d/copr-keygen.conf
                name: copr-keygen
                subPath: copr-keygen.conf
          volumes:
            - name: copr-keygen-data
              persistentVolumeClaim:
                claimName: copr-keygen-data
            - name: copr-keygen
              configMap:
                name: copr-keygen
          restartPolicy: OnFailure
