---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: copr-redis
  namespace: fedora-copr-prod
spec:
  replicas: 0
  strategy:
    type: Recreate
  selector:
    matchLabels:
      component: copr-redis
  template:
    metadata:
      labels:
        component: copr-redis
    spec:
      nodeSelector:
        usage: test
        os.architecture: amd64
      containers:
        - image: centos/redis-32-centos7
          imagePullPolicy: IfNotPresent
          name: copr-redis
          livenessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -i
                - -c
                - test "$(redis-cli -h 127.0.0.1 ping)" == "PONG"
            initialDelaySeconds: 5
            timeoutSeconds: 5
          resources:
            requests:
              cpu: 500m
              memory: 500Mi
            limits:
              cpu: 1000m
              memory: 1000Mi
          ports:
            - containerPort: 6379
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/redis/data
              name: redis-data
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: copr-redis-data