apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openeuler-usercenter
commonAnnotations:
  kubernetes.ops.cluster: openeuler-hk-cluster
  kubernetes.ops.email: ""
  kubernetes.ops.os.base: ubuntu
  kubernetes.ops.owner: chenyang
  kubernetes.ops.region: hk
resources:
- ingress.yaml
- service.yaml
- deployment.yaml
- secret.yaml
