---
apiVersion: v1
kind: Service
metadata:
  name: web-server
  labels:
    app: web-server
  namespace: discourse
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: web-server
  sessionAffinity: None
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server
  namespace: discourse
spec:
  replicas: 4
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: web-server
  template:
    metadata:
      labels:
        app: web-server
    spec:
      containers:
      - name: web-server
        image: swr.cn-north-4.myhuaweicloud.com/opensourceway/common/discourse:v1.1.8
        command: ["/sbin/boot"]
        ports:
        - containerPort: 80
        env:
        - name: DISCOURSE_DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: discourse-secret
              key: discourse_database_username
        - name: DISCOURSE_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: discourse-secret
              key: discourse_database_password
        - name: DISCOURSE_DB_HOST
          valueFrom:
            secretKeyRef:
              name: discourse-secret
              key: discourse_db_host
        - name: DISCOURSE_DB_NAME
          valueFrom:
            secretKeyRef:
              name: discourse-secret
              key: discourse_db_name
        - name: DISCOURSE_REDIS_HOST
          valueFrom:
            secretKeyRef:
              name: discourse-secret
              key: discourse_redis_host
        - name: DISCOURSE_DEVELOPER_EMAILS
          valueFrom:
            secretKeyRef:
              name: discourse-secret
              key: discourse_developer_emails
        - name: DISCOURSE_HOSTNAME
          valueFrom:
            secretKeyRef:
              name: discourse-secret
              key: discourse_hostname
        - name: DISCOURSE_SMTP_ADDRESS
          valueFrom:
            secretKeyRef:
              name: discourse-secret
              key: discourse_smtp_address
        - name: DISCOURSE_SMTP_PORT
          valueFrom:
            secretKeyRef:
              name: discourse-secret
              key: discourse_smtp_port
        - name: DISCOURSE_SMTP_USER_NAME
          valueFrom:
            secretKeyRef:
              name: discourse-secret
              key: discourse_smtp_username
        - name: DISCOURSE_SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: discourse-secret
              key: discourse_smtp_password
        - name: DISCOURSE_SMTP_ENABLE_START_TLS
          valueFrom:
            secretKeyRef:
              name: discourse-secret
              key: discourse_smtp_enable_start_tls
        - name: DISCOURSE_SMTP_AUTHENTICATION
          valueFrom:
            secretKeyRef:
              name: discourse-secret
              key: discourse_smtp_authentication
        - name: SENSITIVE_DOMAIN_NAME
          valueFrom:
            secretKeyRef:
              name: discourse-secret
              key: sensitive_domain_name
        - name: SENSITIVE_NAME
          valueFrom:
            secretKeyRef:
              name: discourse-secret
              key: sensitive_name
        - name: SENSITIVE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: discourse-secret
              key: sensitive_password
        resources:
          requests:
            cpu: 1
            memory: 2000Mi
          limits:
            cpu: 2
            memory: 4000Mi
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: discourse-storage
          mountPath: /shared
      volumes:
      - name: discourse-storage
        persistentVolumeClaim:
          claimName: discourse-share-volume-sfs-turbo