---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: discourse-share-volume-sfs-turbo
  namespace: discourse
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
        storage: 500Gi
  storageClassName: csi-sfsturbo
  volumeMode: Filesystem
  volumeName: pv-efs-discourse-share-volume