resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - pvc.yaml
  - namespace.yaml
commonLabels:
  app: openeuler-oqserver
commonAnnotations:
  owner: wangshaobo
  email: "bobo.shaobowang@huawei.com"
namespace: openeuler-oqserver
