---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: repo-nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
  name: openlookeng-tryme-test-new-ingress
  namespace: openlookeng-tryme-test
spec:
  tls:
    - hosts:
        - tryme.openlookeng.test.osinfra.cn
      secretName: openlookeng-tryme-test-new-tls
  rules:
    - host: tryme.openlookeng.test.osinfra.cn
      http:
        paths:
          - backend:
              serviceName: openlookeng-tryme-test-internal
              servicePort: 80
            path: /
