---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dockerhub-volume
  namespace: openeuler-dockerhub
  annotations:
    everest.io/disk-volume-type: SSD
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1000Gi
  storageClassName: csi-disk
  volumeMode: Filesystem