---
apiVersion: v1
kind: Service
metadata:
  name: dockerhub
  namespace: openeuler-dockerhub
spec:
  ports:
  - name: httpport
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: dockerhub
  type: ClusterIP