---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    everest.io/disk-volume-type: GPSSD
  name: cce-evs-gitlab-data
  namespace: source-gitlab
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2000Gi
  storageClassName: csi-disk
  volumeMode: Filesystem
  volumeName: pv-evs-source-gitlab-from-old-cluster

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    everest.io/disk-volume-type: GPSSD
  name: cce-evs-redis-data
  namespace: source-gitlab
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  storageClassName: csi-disk
  volumeMode: Filesystem
  volumeName: pv-evs-source-gitlab-redis-from-old-cluster