resources:
- deployment.yaml
- ingress.yaml
- service.yaml
commonAnnotations:
  kubernetes.ops.cluster: openeuler-hk-cluster
  kubernetes.ops.email: chenzeng765@163.com
  kubernetes.ops.os.base: openeuler
  kubernetes.ops.owner: chenzeng
  kubernetes.ops.region: hk
namespace: openeuler-mirrorlist-server
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/openeuler/mirrorlist-server
  newTag: 42f3f7a0af824ddfe17ca19844cf2f4b008a0d15
