resources:
- deployment.yaml
- configmap.yaml
commonAnnotations:
  kubernetes.ops.cluster: openeuler-hk-cluster
  kubernetes.ops.email: 348134071@qq.com
  kubernetes.ops.os.base: Alpine
  kubernetes.ops.owner: yangwei
  kubernetes.ops.region: hk
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openeuler-software-pkg
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/openeuler/software-package-github-server
  newTag: fe20ae2b1dc26f58d47ed8ce1caee90b9a57e68d
