---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/permanent-redirect: 'https://www.openeuler.org/en/'
    nginx.ingress.kubernetes.io/rewrite-target: /
  name: website-ru-ingress-main
  namespace: website-v2
spec:
  rules:
    - host: ru.openeuler.org
      http:
        paths:
          - backend:
              serviceName: website-frontend-service
              servicePort: 80
            path: /
  tls:
  - hosts:
    - ru.openeuler.org
    secretName: website-ru-tls-main-secret
