apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- configmap.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
commonAnnotations:
  kubernetes.ops.cluster: openeuler-hk-cluster
  kubernetes.ops.email: chenzeng765@163.com
  kubernetes.ops.os.base: Alpine
  kubernetes.ops.owner: chenzeng
  kubernetes.ops.region: hk
namespace: openeuler-software-pkg
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/robot/robot-gitee-hook-delivery
  newTag: master-b1d6e59