apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: cve-backend-info
  name: cve-backend-info
spec:
  replicas: 0
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: cve-backend-info
  template:
    metadata:
      labels:
        app: cve-backend-info
    spec:
      containers:
        - env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: cve-secrets
                  key: db-username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cve-secrets
                  key: db-passwd
            - name: DB_URI
              valueFrom:
                secretKeyRef:
                  name: cve-secrets
                  key: db-uri
            - name: UPLOAD_USERNAME
              valueFrom:
                secretKeyRef:
                  name: cve-secrets
                  key: upload-username
            - name: UPLOAD_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cve-secrets
                  key: upload-password
            - name: TZ
              value: Asia/Shanghai
          image: swr.cn-north-4.myhuaweicloud.com/opensourceway/openeuler/cve-backend:1af0e89aa0c00772d1f74db0bf0620e94c4f3ae6
          imagePullPolicy: IfNotPresent
          name: cve-backend-infod
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
