resources:
- openeuler-docs-ci.yaml
- secrets.yaml
commonLabels:
  app: openeuler-jenkins
  owner: liuqi
commonAnnotations:
  kubernetes.ops.cluster: openeuler-cn4-jenkins-mix
  kubernetes.ops.email: nicliuqi@gmail.com
  kubernetes.ops.os.base: openEuler
  kubernetes.ops.owner: liuqi
  kubernetes.ops.region: beijing
namespace: jenkins
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/common/openeuler-docs-ci
  newTag: v1
