resources:
- https://github.com/opensourceways/compass-ci/deploy?ref=master
- ingress.yaml
- secret.yaml
commonLabels:
  app: compass-ci
  owner: dukaitian
commonAnnotations:
  email: huming15@163.com
  owner: dukaitian
namespace: compass-ci
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: opensourceway/compassciweb
  newName: swr.ap-southeast-1.myhuaweicloud.com/opensourceway/compassciweb
  newTag: 18741183383c9513e99df71d67bb5e998f449f08.1600853199
- name: swr.ap-southeast-1.myhuaweicloud.com/opensourceway/compassciweb
  newName: swr.cn-north-4.myhuaweicloud.com/opensourceway/openeuler/compassciweb
  newTag: a1cd623b18ba642f0b7ccd8f561975a8ffc72c02.1620722472
- name: swr.cn-north-4.myhuaweicloud.com/opensourceway/openeuler/compassciweb
  newTag: 2312f124b2ce5e81cf05009d2dff5f3cbd3aa848.1672278474
