apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: compass-ci-tls
  namespace: compass-ci
spec:
  name: compass-ci-tls
  keysMap:
    ca.crt:
      path: secrets/data/openeuler/openeuler-org-tls
      key: server.crt
    tls.crt:
      path: secrets/data/openeuler/openeuler-org-tls
      key: server.crt
    tls.key:
      path: secrets/data/openeuler/openeuler-org-tls
      key: server.key