resources:
- pvc.yaml
- namespace.yaml
- secrets.yaml
- ingress.yaml
- deployment.yaml
- service.yaml
- configmap.yaml
commonLabels:
  app: openeuler-repo-mirror-france
commonAnnotations:
  owner: liuyang
  email: "747802914@qq.com"
namespace: repo-mirror
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
